### ISSUE TITLE
Rating from high to low

### ISSUE THREAD

**Issue by ilyassakhanov** [Slemanof/restaurant_recommender_2001#111]
On the website, sort option by default is set as "Rating from high to low". But it doesn't sort by the rating.

**To Reproduce**
Go to the our website. Watch the order of ratings

**Expected behaviour**
The restaurants should be ordered from high rating to low by default or empty field as default sort.

**Comment by ya-iris** [comment]
Actually, sorting has no default value, so it is not applied at all from the beginning. Instead, the first value from the dropdown menu is simply visible. But I will try to fix it, so there is no impression of it being applied and not working
