### ISSUE TITLE
Functional testing protocols

### ISSUE THREAD

**Issue by svarnypetr** [Slemanof/restaurant_recommender_2001#119]
Describe user interaction scenarios with the application and test them.

- [x] Come up with a series of user interactions (5+) with the application.
- [x] Describe them so that they can be replicated precisely -> testing protocol documents for each interaction and template for reporting.
- [x] Try them on the app and provide reports for the testing.

**Comment by svarnypetr** [comment]
Each scenario has a basic intention description:
"I am hungry at Prague College at my desktop PC and want to go for a burger but not sure if they are still open."
And a step by step "guide" how to get there in the app:
1. open webpage in browser
2. write address to address bar
3. open cuisine dropdown
4. select burger
...

And followed by a protocol that contains:
1. Date when the test was done (ideally also the version of the software).
2. What steps were taken.
3. What problems were encountered and at what step (ideally supported with printscreen or similar evidence).
4. Suggestion for improvement (if turned into issues, they should be referenced in the document).

**Comment by svarnypetr** [comment]
Example sources @donnelmandimika :
[test.io Functional testing](https://test.io/functional-testing/)
[softwarecarpentry Functional testing](https://www.softwaretestinghelp.com/functional-testing-interview-questions/)

**Comment by donnelmandimika** [comment]
[User interaction scenarios.pdf](https://github.com/Slemanof/easyeats.live/files/4676809/User.interaction.scenarios.pdf)

Each user interaction scenario included and scenario as well as a step by step as to how the user went about using the application. Protocol is also included in each scenario, the protocol consists of the time, problems faced, and suggested improvements for the application. All the  user interaction scenarios used the same template and structure.
