### ISSUE TITLE
Filtering Algorithm

### ISSUE THREAD

**Issue by Slemanof** [Slemanof/restaurant_recommender_2001#12]
Developing algorithm that will filter data based on user's interaction.

- [x] Saves user tag choices
- [ ] Saves restaurant tag choices
- [ ] Performs a search query via comparison (set/ list compare, etc.)
- [ ] Returns a list of restaurants sorted by similarity(not yet defined)
- [ ] Allows user to clear selected preferences and begin anew

**Comment by DeC0rtez** [comment]
Added a .py file to development branch. Simple python functions which allow user to select some options via input. Further plan is to transfer these options into a data structure which will allow for comparison between user input and restaurant input to be used in "matchmaking" (recommendation). Work in progress.

note: not assigned to this issue in particular, was not sure wether relevant to **filtering algorithm** or **user data**

**Comment by svarnypetr** [comment]
This is why the issue descriptions should be clear ASAP. If they are ambiguous two devs can work on the same thing without knowing so and even worse, it can lead to duplicate functionalities and unclear dependencies in the code.

**Comment by DeC0rtez** [comment]
Description updated to checklist with some details.

**Comment by DeC0rtez** [comment]
Requirements meant to be addressed by this issue are covered elsewhere and thus development on this issue is concluded.

**Comment by DeC0rtez** [comment]
Issue closed.
