### ISSUE TITLE
Security Checklist - System BackUp

### ISSUE THREAD

**Issue by Stanley008** [Slemanof/restaurant_recommender_2001#120]
Restaurant Recommender Security Checklist advices to use a system backup solution to backup all the data in case of a failure, unknown threats . A solution will be prepared with 3-2-1 BackUp strategy rules.

**Comment by Slemanof** [comment]
Back up is enabled now on DigitalOcean for the whole droplet.

@svarnypetr can we consider GitHub also another back-up?

**Comment by svarnypetr** [comment]
@Slemanof  Yep, I would say so.

**Comment by Slemanof** [comment]
Perfect, then now we are following the 3-2-1 rule:

- DigitalOcean Backup
- GitHub
- Local backup
The issue will be closed.

**Comment by Stanley008** [comment]
The BackUp was made also on private Server with redundancy RAID set to 1. Everyday backup at midnight is made(can be changed to as many times as wanted) and BackUps are kept for 30days(can be adjusted), afterwards always the oldest gets deleted and renewed by a new one. 

The rules of safe BackUp were met, with another backup solutions mentioned in comment above.

A script was used: 

#!/bin/sh
set -ex
USER="Stanley008"
API_URL="https://api.github.com/users/${USER}/repos?type=owner&per_page=100"
DATE=$(date +"%Y%m%d")
TEMP_FOLDER="backup_easyeats"
TEMP_PATH="/volume1/github"
TEMP_FULL_PATH="${TEMP_PATH}/${TEMP_FOLDER}"
BACKUP_FILE="github_${USER}_${DATE}.tar.xz"
rm -rf "$TEMP_FULL_PATH"
mkdir "$TEMP_FULL_PATH" && cd "$TEMP_FULL_PATH"
curl -s "$API_URL" | grep -Eo '"git_url": "[^"]+"' | grep -v "[Ff]ubu" | grep -v "bottles" | grep -v "stripe\.net" | awk '{print $2}' | xargs -n 1 /volume1/@appstore/git/bin/git clone
cd ${TEMP_PATH}
tar -Jcf "$BACKUP_FILE" --directory="$TEMP_PATH" "$TEMP_FOLDER"
rm -rf "$TEMP_FULL_PATH"
find /volume1/github/backup_easyeats/*.xz -type f -mtime +30 -delete
