### ISSUE TITLE
OWASP

### ISSUE THREAD

**Issue by donnelmandimika** [Slemanof/restaurant_recommender_2001#14]
Application fits all the top 10 OWASP requirements :

- [x] Evaluating GitHub auto scan
- [x] Preparing guidelines for developers
- [x] Prepare simple test for Pytest

**Comment by svarnypetr** [comment]
How come this is not worked on if it contains also guidelines for developers? Those should be ready before developers start adding code to the project.

**Comment by riccardosl** [comment]
> 
> 
> How come this is not worked on if it contains also guidelines for developers? Those should be ready before developers start adding code to the project.

Apologies, we have a Security Checklist as draft, feedback appreciated:
https://github.com/Slemanof/restaurant_recommender_2001/blob/testing/security_checklist.md

**Comment by Stanley008** [comment]
Updated security checklist was provided. Please continue to discuss further security matter in provided discussion thread: https://github.com/Slemanof/restaurant_recommender_2001/issues/28
