### ISSUE TITLE
Recommendations

### ISSUE THREAD

**Issue by Slemanof** [Slemanof/restaurant_recommender_2001#17]
Recommendation system development based on restaurants liked by the user and added to the restaurant_user junction table by their id corresponding to the user's id

**Comment by ilyassakhanov** [comment]
I don't understand what am I required to do.

**Comment by svarnypetr** [comment]
@jandvorak-dot Update the description to reflect what you are working on - what is the outcome, what is the suggested solution etc.

**Comment by jandvorak-dot** [comment]
created a branch which has algorithm to recommend based on user likes. Will need to expand it once we have a user database designed.

**Comment by svarnypetr** [comment]
> created a branch which has algorithm to recommend based on user likes. Will need to expand it once we have a user database designed.

@jandvorak-dot A good approach is to tie the branch directly to a WIP merge request and then you can reference it in such comments.

**Comment by ilyassakhanov** [comment]
@jandvorak-dot The user database is ready on develop branch
