### ISSUE TITLE
User database

### ISSUE THREAD

**Issue by donnelmandimika** [Slemanof/restaurant_recommender_2001#19]
Modify an SQL script to contain tables for users, also create a script that would add that data to the database with applied security measures(i.e encryption, hasing)

**Comment by DeC0rtez** [comment]
Added a .py file to development branch. Simple python functions which allow user to select some options via input. Further plan is to transfer these options into a data structure which will allow for comparison between user input and restaurant input to be used in "matchmaking" (recommendation). Work in progress.

**Comment by svarnypetr** [comment]
- If it is only part of the should level, why is it already in the development branch, is it planned already as part of the next release? If this is just a small experiment that will not be part of the next (i.e. first) release, then it should not obfuscate the development branch but sit on its own experimental branch.
- If it is work in progress, why is it only in Todo and not In Process? Similar as before, if this was just a personal attempt, then the issue (which is super broad) should reflect it.

**Comment by DeC0rtez** [comment]
Corrected - new branch **filtering-algorithm** created. File moved from **develop** to **filterning-algorithm** & project boards updated from **To Do** -> **In Process**.
