### ISSUE TITLE
Try to collect data from Zomato

### ISSUE THREAD

**Issue by svarnypetr** [Slemanof/restaurant_recommender_2001#24]
Write a prototype that accesses the data from Zomato for:
 - [x] name
 - [x] address
 - [x] price
 - [x] opening hours
 - [x] vegan option
 - [ ] menu 
 - [x] lunch menu

### Definition of done:
- [ ] clarified for all  data above whether it can be collected from the service or not
- [ ] example script that can collect the data

**Comment by ilyassakhanov** [comment]
Impossible to extract menu
