### ISSUE TITLE
Try to collect data from Yelp

### ISSUE THREAD

**Issue by svarnypetr** [Slemanof/restaurant_recommender_2001#25]
Write a prototype that accesses the data from Yelp for:
 - [x] name
 - [x] address
 - [x] price
 - [ ] opening hours
 - [x] vegan option
 - [ ] menu 
 - [ ] lunch menu

### Definition of done:
- [ ] clarified for all  data above whether it can be collected from the service or not
- [ ] example script that can collect the data

**Comment by ilyassakhanov** [comment]
Couldn't find any menu on yelp.cz

**Comment by ilyassakhanov** [comment]
I got banned from yelp  and since there is no menu on yelp, shall be switching to google_api
