### ISSUE TITLE
Try to collect data from Dame jidlo

### ISSUE THREAD

**Issue by svarnypetr** [Slemanof/restaurant_recommender_2001#26]
Write a prototype that accesses the data from Zomato for:
 - [ ] name
 - [ ] address
 - [ ] price
 - [ ] opening hours
 - [ ] vegan option
 - [ ] menu 
 - [ ] lunch menu

### Definition of done:
- [ ] clarified for all  data above whether it can be collected from the service or not
- [ ] example script that can collect the data

**Comment by Slemanof** [comment]
It didn't work with Cyotek WebCopy, I wasn't able to extract restaurant's info and then my IP got blocked
