### ISSUE TITLE
Hosting

### ISSUE THREAD

**Issue by ilyassakhanov** [Slemanof/restaurant_recommender_2001#3]
Our app should be accessible from the web- that means it should be hosted somewhere

For this ,a hosting server where and how is it going to be deployed should be found.

**Comment by DeC0rtez** [comment]
We can use GithubPages for hosting of the web app. IIRC it is free of charge, +it makes sense to have it all in one place.

**Comment by ilyassakhanov** [comment]
Only the owner of the repository can do anything with the repository page. I am sorry, but your solution won't work

**Comment by Slemanof** [comment]
I will take care of this.

**Comment by Slemanof** [comment]
Hosting bought on DigitalOcean 
Domain name: easyeats.live
