### ISSUE TITLE
Set up automated tests

### ISSUE THREAD

**Issue by ilyassakhanov** [Slemanof/restaurant_recommender_2001#34]
We do not have automated tests for anything, so committed code can be bad.

**To do**
- [x] set up GitHub Action for Flake8 or another coding style test
- [x] set up GitHub Action for pytest (or another testing framework)
- [x] Communicate with team what testing/codig style verification is being used so that they can set up their local environment
- [x] Make sure it is mentioned in appropriate places (contrib guide, security guide?) @Slemanof

**Comment by Slemanof** [comment]
@riccardosl I will start working on, README.md and CONT.md and include the guides from this issue.

**Comment by Slemanof** [comment]
All done and a CONTRIBUTING.md file is created in #testing branch.
