### ISSUE TITLE
Optimize the algorithm that would update daily menu of restaurants

### ISSUE THREAD

**Issue by ilyassakhanov** [Slemanof/restaurant_recommender_2001#40]
Optimize the script on the branch restaurant-data-mysql that has a name update_menu.py
Look into minimizing connections with MySQL database in that script to only one.

**Comment by svarnypetr** [comment]
@jandvorak-dot See https://github.com/Slemanof/easyeats.live/blob/76db1f9d0a1e3ef11e107cc74bb0a6597f05072c/update_menu.py#L56

**Comment by jandvorak-dot** [comment]
Fixed
