### ISSUE TITLE
JSON to dictionary converter

### ISSUE THREAD

**Issue by ilyassakhanov** [Slemanof/restaurant_recommender_2001#46]
Write a script that would convert menu in JSON into a menu in a python dictionary
Example of a menu in JSON:
{"status": "success", "daily_menus": [{"daily_menu": {"name": "Jídlo s sebou", "dishes": [{"dish": {"name": "Jídlo a nápoje prodáváme pouze v okénku. Máme otev?eno ka?dý den od 8:00 do 18:00. Nov? si nás m??ete objednat také skrze portál Dáme jídlo a Wolt.", "price": "", "dish_id": "702862226"}}, {"dish": {"name": "PE?IVO", "price": "", "dish_id": "702862227"}}, {"dish": {"name": "Chléb Savoy", "price": "68 K?", "dish_id": "702862228"}}]}

**Comment by svarnypetr** [comment]
Nasty, they use the 'dish' member also to announce the new opening hours/limitations.

**Comment by DeC0rtez** [comment]
Code integrated into project by Iryna. Currently doing tests for said code.

**Comment by DeC0rtez** [comment]
PyTests written for **converter.py** file which extracts desired data from a .json file and stores it in a python dictionary. Available in the json-to-dict-converter branch as **test_converter.py** .
