### ISSUE TITLE
Create logo

### ISSUE THREAD

**Issue by ya-iris** [Slemanof/restaurant_recommender_2001#49]
Create a logo for the application to use in the app styling

**Comment by svarnypetr** [comment]
Add to branch 049_create_logo.

**Comment by Stanley008** [comment]
A Logo was created with App name and Slogan. It was submitted to frontend. 

https://github.com/Slemanof/easyeats.live/tree/frontend/Easy%20Eats%20Logos

**Comment by Slemanof** [comment]
Issue Duplication #52 already solved.

**Comment by svarnypetr** [comment]
Logos were added to the Frontend branch. #52 was used more for educational purposes.
