### ISSUE TITLE
Website Hosting - Own Server

### ISSUE THREAD

**Issue by Stanley008** [Slemanof/restaurant_recommender_2001#50]
A web server is going to be hosted public, main challenge is to get a free website domain and working public link due to security reasons and provider public/non public IPs.

**Comment by Stanley008** [comment]
Due to security reasons approved ports had to be opened.

**Comment by Stanley008** [comment]
IPv6 non public ip made a lot of issues, due to this reason IPv4 and public IP was requested from ISP.

**Comment by ilyassakhanov** [comment]
This issue looks like a duplicate to issue #3

**Comment by Slemanof** [comment]
Duplication as @ilyassakhanov mentioned with issue #3. already resolved.

**Comment by Stanley008** [comment]
Domain name.com website was connected to private server with appropriate IPV4 addresses. Domain name easyeats.live was interconnected.
