### ISSUE TITLE
Input Validation and Sanitization rules. 

### ISSUE THREAD

**Issue by Slemanof** [Slemanof/restaurant_recommender_2001#61]
> Validation checks if the input meets a set of criteria (such as a string contains no standalone single quotation marks).
> 
> Sanitization modifies the input to ensure that it is valid (such as doubling single quotes).
> 
> You would normally combine these two techniques to provide in-depth defense to your application. For example, you might change all single quotation marks in a string to double quotation marks (sanitize) and then check that all the quotation marks were actually changed to double quotation marks (validate).
> 
> Validation checks include testing for the length, format, range, and allowable characters. For example, if your application expects positive integer input, you need to validate that any string input consists only of the digits 0 through 9.

This issue is partially mentioned in the [security_checklist](https://github.com/Slemanof/easyeats.live/blob/testing/security_checklist.md), we have to discuss how to apply this on our application.

**Comment by Stanley008** [comment]
Here are suggestions for testing:

Restaurant = No more than 50 characters.

Location = up to 9 numbers + 9 numbers

Address = No more than 40 characters.

Rating = No more than 2 digits. No more than 3 characters. (example: 3.6)

Cuisines = No more than 20 characters.

Featured Image = ? test for jpg ?

Highlights = No more than 50 characters.

Phone Number = + 12 numbers or 14 numbers. Delete space and check for +12numbers or only 14 numbers.

PS: These are not final limitations, they can be adjusted accordingly to other team needs.

**Comment by Slemanof** [comment]
@Stanley008 could you double check this and how to apply it?

**Comment by Stanley008** [comment]
Input Validitation and Sanitization was covered during classes.
