### ISSUE TITLE
Website hosting and website domain interconnection - Set Up

### ISSUE THREAD

**Issue by Stanley008** [Slemanof/restaurant_recommender_2001#68]
A set up for connecting website hosting and website domain name will be done, to be able to host wordpress or any other webpage needed things.

**Comment by Stanley008** [comment]
Digital Ocean is having technical issues with: "An unknown error has occurred." , hopefully they will be up soon to set needed connection for web.

**Comment by Slemanof** [comment]
DigitalOcean error was handled, it was due to login options changes. all works fine now.

**Comment by Stanley008** [comment]
Digital Ocean setup was done and Comming Soon - Website was pushed online and can be viewed. 

easyeats.live
