### ISSUE TITLE
Collect restaurant data: name, address, price, opening hours, vegan option, menu & lunch menu

### ISSUE THREAD

**Issue by ya-iris** [Slemanof/restaurant_recommender_2001#8]
Exploratory collection of data from restaurants:
- [x] #24 Zomato
- [x] #25 Yelp
- [x] #26 Dame jidlo

**Comment by svarnypetr** [comment]
In general, a good approach is to have only one person assigned to an issue, especially as issue=branch. If there is too much work on one issue, it should be split into manageable chunks.
