### ISSUE TITLE
Test json to dictionary converting script

### ISSUE THREAD

**Issue by DeC0rtez** [Slemanof/restaurant_recommender_2001#84]
Writing tests for converter.py file which extracts desired data from a .json file and stores it in a python dictionary.

**Comment by svarnypetr** [comment]
@DeC0rtez  Why is this a new issue, writing unittests should be part of writing the code itself, i.e. the original issue #46

**Comment by DeC0rtez** [comment]
Mistake corrected, relevant information mentioned in issue #46
