### ISSUE TITLE
Deploy automated tests

### ISSUE THREAD

**Issue by svarnypetr** [Slemanof/restaurant_recommender_2001#93]
The `testing-hide-api2` branch contains the fundaments of automated testing (see `.github/workflow/`).

These must be deployed in the `develop` branch, i.e. merge the automated tests to `develop` and make sure they work properly with the tests that are currently there.

Any future addition of code should already contain relevant tests and run the automated testing pipeline.

**Comment by Slemanof** [comment]
Issue was solved with merge #100
